name: Sync Post

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: "30 1 * * *"
  issues:
    types:
      - opened
      - closed
      - labeled
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Git config ğŸ”§
        run: |
          git config --global user.name "giscafer"
          git config --global user.email "giscafer@outlook.com"

      - name: Display runtime info âœ¨
        run: |
          echo 'å½“å‰ç›®å½•ï¼š'
          pwd

      - name: Install ğŸ”§
        run: yarn install

      # - name: Build â›ï¸
      #   run: yarn build

      - name: Update blog files â›ï¸
        run: |
          yarn sync-post
          git add .
          git commit -m 'chore: sync post'
          git push
